### ISSUE TITLE
Cannot list test cases from a process running inside WSL2

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/vscode-boost-test-adapter#1]
Seems like there are some problems on spawning a Linux process from Windows space.

**Comment by psolstice** [comment]
Configuration:
Windows 10 2004, WSL2 (Ubuntu 18.04). Plugin is installed on WSL side and running in Linux environment

Result:
Test pane is empty

Log:
```
[2020-04-07 06:59:02.088] [INFO] Creating adapter for /home/peter/zcoin-core14
[2020-04-07 06:59:02.088] [INFO] Registering adapter for /home/peter/zcoin-core14
[2020-04-07 06:59:02.090] [INFO] Initialization finished
[2020-04-07 06:59:02.993] [ERROR] [peg$SyntaxError: Expected "digraph", "graph", or "strict" but "B" found.
	at peg$buildStructuredError (/home/peter/.vscode-server/extensions/zcoinofficial.boost-test-adapter-2.0.0/node_modules/dotparser/grammar/dot.js:520:12)
	at peg$parse (/home/peter/.vscode-server/extensions/zcoinofficial.boost-test-adapter-2.0.0/node_modules/dotparser/grammar/dot.js:2938:11)
	at TestExecutable.listTest (/home/peter/.vscode-server/extensions/zcoinofficial.boost-test-adapter-2.0.0/lib/test-executable.js:49:24)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
	at async BoostTestAdapter.load (/home/peter/.vscode-server/extensions/zcoinofficial.boost-test-adapter-2.0.0/lib/adapter.js:47:37)] {
  message: 'Expected "digraph", "graph", or "strict" but "B" found.',
  expected: [
    { type: 'literal', text: 'strict', ignoreCase: true },
    { type: 'literal', text: 'graph', ignoreCase: true },
    { type: 'literal', text: 'digraph', ignoreCase: true }
  ],
  found: 'B',
  location: {
    start: { offset: 0, line: 1, column: 1 },
    end: { offset: 1, line: 1, column: 2 }
  },
  name: 'SyntaxError'
}
```

Output of `test_bitcoin --list_content=DOT`:
[test_bitcoin_output.txt](https://github.com/zcoinofficial/vscode-boost-test-adapter/files/4443095/test_bitcoin_output.txt)
